CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = 
EXAMPLESF       = ex2c.c ex2d_MMS.c
MANSEC          = TS
DIRS            = toy-problem
CLEANFILES      = SA-data/*
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

all: ex2c ex2d_MMS
.PHONY: all
