on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds RDycore and runs our test suite.
  build:
    runs-on: ${{ matrix.os }}
    container: coherellc/rdycore-petsc:v3.18.4

    # A build matrix storing all desired configurations.
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        build-type: [Debug] #, Release]

    # Steps for building and running tests.
    steps:

    - name: Checking out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build swe_roe demos (${{ matrix.build-type }})
      run: |
        cd swe_roe
        make ex1
        ./ex1 -hd 5.0 -save 2 -b -dx 10 -dy 10 -dt 0.01 -ts_max_time 0.1
        mpiexec -n 3 ./ex1 -domain 1 -dt 0.01 -t 1.0
        make ex2a
        ./ex2a -dm_view -save -b  -hu 10.0 -hd 5.0 -save -dt 0.01 -ts_monitor -Nx 200 -Ny 200  -b -ts_max_time 0.1
        mpiexec -n 3 ./ex2a -dm_view -save -b  -hu 10.0 -hd 5.0 -save -dt 0.01 -ts_monitor -Nx 200 -Ny 200  -b -ts_max_time 0.1
        make ex2b
        mpiexec -n 3 ./ex2b -dm_view -save -b  -hu 10.0 -hd 5.0 -save -dt 0.01 -ts_monitor -Nx 200 -Ny 200  -b -ts_max_time 0.1
        mpiexec -n 3 ./ex2b -mesh ../share/meshes/DamBreak_grid5x10.exo -initial_condition ../share/initial_conditions/DamBreak_grid5x10_wetdownstream.IC -dt 0.01 -ts_max_time 0.1
        mpiexec -n 3 ./ex2b -mesh ../share/meshes/Turning_1000_1000_dhdx1_with_z.exo -initial_condition ../share/initial_conditions/IC_Turning_1000_1000_dhdx1_with_z.bin -dt 10 -Nt 10 -mannings_n 0.015 -use_critical_flow_bc -boundary_edge_type_file ../share/auxfiles/Turning_1000_1000_dhdx1_with_z_bc_edge_type_critical_outflow.bin
